/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Successful Response
 */
export type AlgoritmosDisponiveisAlgoritmosGet200 = string[]

export type AlgoritmosDisponiveisAlgoritmosGetQueryResponse = AlgoritmosDisponiveisAlgoritmosGet200

export type AlgoritmosDisponiveisAlgoritmosGetQuery = {
  Response: AlgoritmosDisponiveisAlgoritmosGet200
  Errors: any
}