/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PontoDTO } from './PontoDTO.ts'

export type AlgoritmosDto = {
  /**
   * @description Alias do algoritmo que sera utilizado
   * @type string
   */
  algoritmo: string
  /**
   * @description Ponto de partida
   * @type object
   */
  ponto_inicial: PontoDTO
  /**
   * @description Lista de pontos de interesse
   * @type array
   */
  pontos_interesse: PontoDTO[]
}