/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MetricaDto } from './MetricaDto'

export type AlgoritmosResponseDto = {
  /**
   * @description Alias do algoritmo que sera utilizado
   * @type string
   */
  algoritmo: string
  /**
   * @description Ruas para traçar
   * @type array
   */
  caminho: [number, number][]
  /**
   * @description Objeto com as metricas dos algoritmos
   * @type array
   */
  metricas: MetricaDto[]
  /**
   * @description menor caminho em (m)
   * @type number
   */
  menorCaminho: number
  /**
   * @description Ruas selecionadas pelo agoritmo
   * @type array
   */
  ruas: any[]
}