/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TipoAlgoritmo } from './TipoAlgoritmo.ts'

export type AlgoritmosResponseDto = {
  /**
   * @description Alias do algoritmo que sera utilizado
   * @type string
   */
  algoritmo: TipoAlgoritmo
  /**
   * @description Objeto com as metricas dos algoritmos
   * @type object
   */
  metricas: {
    [key: string]: string
  }
  /**
   * @description menor caminho em (m)
   * @type number
   */
  menorCaminho: number
  /**
   * @description Ruas selecionadas pelo agoritmo
   * @type array
   */
  ruas: any[]
}