/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AlgoritmosDto } from './AlgoritmosDto'
import type { AlgoritmosResponseDto } from './AlgoritmosResponseDto'
import type { HTTPValidationError } from './HTTPValidationError'

/**
 * @description Successful Response
 */
export type CalcularRotaAlgoritmosPost200 = AlgoritmosResponseDto

/**
 * @description Validation Error
 */
export type CalcularRotaAlgoritmosPost422 = HTTPValidationError

export type CalcularRotaAlgoritmosPostMutationRequest = AlgoritmosDto

export type CalcularRotaAlgoritmosPostMutationResponse = CalcularRotaAlgoritmosPost200

export type CalcularRotaAlgoritmosPostMutation = {
  Response: CalcularRotaAlgoritmosPost200
  Request: CalcularRotaAlgoritmosPostMutationRequest
  Errors: CalcularRotaAlgoritmosPost422
}