/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Successful Response
 */
export type GetAllPoisPoisGet200 = any

export type GetAllPoisPoisGetQueryResponse = GetAllPoisPoisGet200

export type GetAllPoisPoisGetQuery = {
  Response: GetAllPoisPoisGet200
  Errors: any
}