/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type MetricaDto = {
  /**
   * @description Nome da métrica
   * @type string
   */
  name: string
  /**
   * @description Descrição da métrica
   * @type string
   */
  description: string
  /**
   * @description Resultado da métrica
   * @type string
   */
  result: string
}