/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Successful Response
 */
export type PingGet200 = any

export type PingGetQueryResponse = PingGet200

export type PingGetQuery = {
  Response: PingGet200
  Errors: any
}