/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PontoDTO = {
  /**
   * @description Latitude do ponto
   * @type number
   */
  latitude: number
  /**
   * @description Longitude do ponto
   * @type number
   */
  longitude: number
  /**
   * @description Nome do ponto
   * @type string
   */
  name: string
}