/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const tipoAlgoritmoEnum = {
  FORCA_BRUTA: 'FORCA_BRUTA',
  QAOA: 'QAOA',
  GENETICO: 'GENETICO',
} as const

export type TipoAlgoritmoEnum = (typeof tipoAlgoritmoEnum)[keyof typeof tipoAlgoritmoEnum]

export type TipoAlgoritmo = TipoAlgoritmoEnum