/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { AlgoritmosDisponiveisAlgoritmosGetQueryResponse } from '../models/AlgoritmosDisponiveisAlgoritmosGet.ts'

function getAlgoritmosDisponiveisAlgoritmosGetUrl() {
  return `http://127.0.0.1:8000/algoritmos/` as const
}

/**
 * @summary Algoritmos Disponiveis
 * {@link /algoritmos/}
 */
export async function algoritmosDisponiveisAlgoritmosGet(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<AlgoritmosDisponiveisAlgoritmosGetQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: getAlgoritmosDisponiveisAlgoritmosGetUrl().toString(),
    ...requestConfig,
  })
  return res.data
}