/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type {
  CalcularRotaAlgoritmosPostMutationRequest,
  CalcularRotaAlgoritmosPostMutationResponse,
  CalcularRotaAlgoritmosPost422,
} from '../models/CalcularRotaAlgoritmosPost.ts'

function getCalcularRotaAlgoritmosPostUrl() {
  return `http://localhost:8000/algoritmos/` as const
}

/**
 * @summary Calcular Rota
 * {@link /algoritmos/}
 */
export async function calcularRotaAlgoritmosPost(
  data: CalcularRotaAlgoritmosPostMutationRequest,
  config: Partial<RequestConfig<CalcularRotaAlgoritmosPostMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data
  const res = await request<
    CalcularRotaAlgoritmosPostMutationResponse,
    ResponseErrorConfig<CalcularRotaAlgoritmosPost422>,
    CalcularRotaAlgoritmosPostMutationRequest
  >({ method: 'POST', url: getCalcularRotaAlgoritmosPostUrl().toString(), data: requestData, ...requestConfig })
  return res.data
}