/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { GetAllPoisPoisGetQueryResponse } from '../models/GetAllPoisPoisGet.ts'

function getGetAllPoisPoisGetUrl() {
  return `http://127.0.0.1:8000/pois` as const
}

/**
 * @summary Get All Pois
 * {@link /pois}
 */
export async function getAllPoisPoisGet(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<GetAllPoisPoisGetQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: getGetAllPoisPoisGetUrl().toString(),
    ...requestConfig,
  })
  return res.data
}