/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { PingGetQueryResponse } from '../models/PingGet.ts'

function getPingGetUrl() {
  return `http://127.0.0.1:8000/` as const
}

/**
 * @summary Ping
 * {@link /}
 */
export async function pingGet(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<PingGetQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: getPingGetUrl().toString(), ...requestConfig })
  return res.data
}